name: RefluxoApi
version: 1.0
main: me.refluxo.refluxoapi.Refluxoapi
authors:
  - Refluxo Development
  - EinfachKonrad
  - officialPlocki
api-version: 1.16
description: API für das Refluxo.me-Netzwerk
