name: RefluxoApi
version: ${project.version}
main: me.refluxo.refluxoapi.Refluxoapi
authors:
  - Refluxo Development
  - EinfachKonrad
  - officialPlocki
api-version: 1.16
description: FICK DICH PLOCKI
